const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const context=vm.createContext({console,setTimeout,clearTimeout,setInterval(){},window:{addEventListener(){}},document:{querySelector(){return null},querySelectorAll(){return []},addEventListener(){}}});
const root=path.resolve(__dirname,'..','public');
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').split("document.addEventListener('click'")[0],context);
for(const file of ['novel-studio.js','ai-control.js','novel-references.js','novel-workbench.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
assert.equal(vm.runInContext('novelFresh().review_storyboards',context),true);
assert.equal(vm.runInContext("novelDefaultTab('shot_review')",context),'shots');
vm.runInContext(`novelView.project={...novelFresh(),phase:'script_review',durations:[15],plan:{summary:'<script>',assets:[{id:'a1',kind:'character',name:'A',description:'safe',prompt:'safe',evidence:'safe'},{id:'a2',kind:'scene',name:'B',description:'safe',prompt:'safe',evidence:'safe'}],episodes:[{id:'e1',title:'<img>',synopsis:'story',source_excerpt:'source',shots:[{id:'s1',title:'<script>',seconds:15,asset_ids:['a1'],action:'<img>',dialogue:'hello',camera:'pan',image_prompt:'image',video_prompt:'video'}]}]}};`,context);
assert.doesNotMatch(vm.runInContext('novelScript(novelView.project)',context),/<script>/);
assert.match(vm.runInContext('novelScript(novelView.project)',context),/plan.episodes.0.shots.0.action/);
vm.runInContext("productionView.assetKind='scene'",context);
assert.match(vm.runInContext('novelAssets(novelView.project)',context),/plan.assets.1.description/);
assert.match(vm.runInContext("novelToolbar({...novelView.project,phase:'shot_review'})",context),/approve_shots/);
assert.match(vm.runInContext('novelShots(novelView.project)',context),/data-production-copy="0"/);
vm.runInContext("novelView.tab='script'",context);
assert.doesNotMatch(vm.runInContext("novelToolbar({...novelView.project,id:'saved',phase:'assets'})",context),/data-novel-command/);
assert.match(vm.runInContext("novelToolbar({...novelView.project,id:'saved',phase:'assets'})",context),/production-current-stage/);
vm.runInContext("novelView.tab='story';productionView.setup=2",context);
vm.runInContext('novelView.project=novelFresh();productionView.setup=2',context);
const setup=vm.runInContext('novelStory(novelView.project)',context);
assert.match(setup,/production-add-model/);
assert.doesNotMatch(setup,/href="#settings"|data-page="control"/);
assert.doesNotMatch(vm.runInContext('novelTeamHTML(novelFresh())',context),/data-page="control"/);
assert.equal(vm.runInContext('novelFresh().review_videos',context),true);
assert.equal(vm.runInContext("novelDefaultTab('video_review')",context),'tasks');
vm.runInContext("novelView.tab='tasks'",context);
assert.match(vm.runInContext("novelToolbar({...novelView.project,id:'saved',phase:'video_review'})",context),/production-approve-videos/);
console.log('PASS guided setup, storyboard gate, episode inspector, original asset indices and escaped content');

vm.runInContext("novelView.project={...novelView.project,phase:'video_review',review_standard:'five_dimensions',plan:{episodes:[{id:'e1',title:'测试集',shots:[{id:'s1',title:'测试镜',seconds:3,action:'人物缓步走向测气台'}]}]},slots:{},jobs:[],video_checks:{},video_reviews:{}}",context);
const review=vm.runInContext('novelTasks(novelView.project)',context);
for(const field of ['stability','action','story','timing','design'])assert.match(review,new RegExp('data-quality-dimension="'+field+'"'));
assert.match(review,/data-quality-notes/);
console.log('PASS five dimension review controls and evidence field');
