const assert=require('node:assert/strict');
const graph=require('../public/visual-graph.js');
const a=graph.make('master'),b=graph.make('shot');
a.versions=[{id:'v1',upload_id:'image1'}];a.active_version_id='v1';
graph.connect([a,b],a.id,b.id);
assert.throws(()=>graph.connect([a,b],b.id,a.id),/循环/);
const data=graph.serialize([a,b],new Set([a.id,b.id]));
const copied=graph.paste(data,[]);
assert.notEqual(copied[0].id,a.id);
assert.deepEqual(copied[1].refs,[copied[0].id]);
assert.equal(copied[0].upload_id,'image1');
assert.equal(copied[0].job_ids.length,0);
const onlyShot=graph.paste(graph.serialize([a,b],new Set([b.id])),[]);
assert.equal(onlyShot[0].refs.length,0);
const sameProject=graph.paste(graph.serialize([a,b],new Set([b.id])),[a,b]);
assert.deepEqual(sameProject[0].refs,[a.id]);
assert.throws(()=>graph.paste({...data,nodes:Array(65).fill(data.nodes[0])},[]));
assert.equal(graph.make('master','character').layout,'sheet');
assert.equal(graph.make('master','character').ratio,'16:9');
assert.equal(graph.make('shot').ratio,'9:16');
const view=graph.fit([a,b],900,700);assert.ok(view.zoom>=.15&&view.zoom<=2);
console.log('Visual graph: copy, connection remapping, cycle guards, templates and fit passed');
